### ISSUE TITLE
Customize "Add Dataset" Button URL Based on Organization Context

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/ckan-docker#41]
## Description
We need to implement functionality to dynamically change the "Add Dataset" button URL based on the current organization context in our CKAN instance. This will allow different organizations to have tailored metadata schemas while maintaining a single CKAN instance.

Currently, the ckan-scheming extension is working properly with multiple dataset schemas (e.g., default dataset schema, MINT dataset schema), but the "Add Dataset" button always points to the default URL regardless of organization context.

## Requirements
- Modify the "Add Dataset" button URL based on the organization a user is currently viewing
- For example:
  - Default: `https://ckan.tacc.utexas.edu/dataset/new`
  - Subsidence project: `https://ckan.tacc.utexas.edu/subsidencedataset/new`
  - MINT project: `https://ckan.tacc.utexas.edu/mintdataset/new`
- Each organization should be mapped to its appropriate dataset schema
- We need to ensure backwards compatibility

## Implementation Approach
1. Create a custom extension or modify existing extension to implement `ITemplateHelpers`
2. Create a helper function that determines the appropriate dataset creation URL based on organization context
3. Modify the templates (likely `organization/read.html`) to use our custom URL generator
4. Configure organization-to-schema mappings in the CKAN configuration

## Related Information
- The ckan-scheming extension is already implemented and working
- Schema examples:
  - MINT schema: https://github.com/In-For-Disaster-Analytics/ckan-docker/blob/main/src/ckanext-dso_scheming/ckanext/dso_scheming/mint_dataset.yaml
  - Default CKAN schema: https://github.com/In-For-Disaster-Analytics/ckan-docker/blob/main/src/ckanext-dso_scheming/ckanext/dso_scheming/ckan_dataset.yaml

## Special Requirements for MINT Dataset
For a dataset to be MINTABLE, the schema must include these fields:
```yaml
- field_name: Temporal Coverage Start
  label: Temporal Coverage Start
  preset: date
- field_name: Temporal Coverage End
  label: Temporal Coverage End
  preset: date
- field_name: MINT Standard Variables
  label: MINT Standard Variables
  help_allow_html: true
  help_text: Add a MINT Standard Variable <a href="https://api.models.mint.tacc.utexas.edu/v1.8.0/standardvariables?username=mint@isi.edu" target="_blank">List of Standard Variables</a>
  repeating_subfields:
    - field_name: Standard Variable Label
      label: Standard Variable Label
      form_placeholder: air__daily_max_of_temperature
```

## Acceptance Criteria
- [ ] When viewing a specific organization page, the "Add Dataset" button points to the appropriate URL for that organization's schema
- [ ] Default organizations still point to the default dataset creation URL
- [ ] Proper error handling is in place if an organization doesn't have a specific schema mapping
- [ ] Documentation is updated to reflect the new functionality
