### ISSUE TITLE
Add MINT-Compatible Fields to Default Dataset Schema

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/ckan-docker#50]
# Issue: Add MINT-Compatible Fields to Default Dataset Schema

## Overview
To ensure all datasets can be used with MINT modeling tools, we need to enhance our default dataset schema with the required mintable properties. These properties include spatial coverage, temporal coverage, and a list of standard variables. This issue outlines the necessary changes to our ckan-scheming implementation.

### 1. Spatial Coverage
We need to implement a spatial coverage selector using a bounding box approach for simplicity and compatibility with MINT. This will:
- Allow users to define geographic boundaries through an interactive map
- Support manual coordinate entry (North/South/East/West)
- Include GeoJSON import functionality
- Store data in a standardized format

### 2. Temporal Coverage
Add date picker fields for the time period covered by the dataset:
- `temporal_coverage_start`: Start date of the data
- `temporal_coverage_end`: End date of the data
- Include validation to ensure proper date ranges

### 3. Standard Variables List
Add support for defining the variables contained in the dataset:
- Implement `mint_standard_variables` as a multiple-entry field
- Add reference link to MINT standard variables catalog
- Support searching and selecting from predefined variables

### Schema Updates
Add the following fields to our default dataset schema:

```yaml
# Spatial Coverage
- field_name: spatial_coverage
  label: Spatial Coverage
  preset: spatial_coverage_selector
  form_placeholder: "Define the geographic area covered by this dataset"
  required: false
  help_text: "Select or draw the geographic area that this dataset covers"

# Temporal Coverage
- field_name: temporal_coverage_start
  label: Temporal Coverage Start
  preset: date
  form_placeholder: "YYYY-MM-DD"
  help_text: "The starting date of the time period covered by the dataset"
  required: false

- field_name: temporal_coverage_end
  label: Temporal Coverage End
  preset: date
  form_placeholder: "YYYY-MM-DD"
  help_text: "The ending date of the time period covered by the dataset"
  required: false

# Standard Variables
- field_name: mint_standard_variables
  label: MINT Standard Variables
  preset: multiple_text
  form_placeholder: "e.g., air__daily_max_of_temperature"
  help_text: "Enter standardized variable names used in this dataset. See the <a href='https://api.models.mint.tacc.utexas.edu/v1.8.0/standardvariables?username=mint@isi.edu' target='_blank'>list of standard variables</a>."
  required: false
```

### Required Development Work

1. **Spatial Coverage Selector**
   - Create a custom form widget with map integration
   - Implement coordinate input fields with validation
   - Add GeoJSON import/export functionality
   - Develop display templates for viewing spatial coverage

2. **Temporal Coverage**
   - Ensure date picker works properly with schema
   - Add validation for proper date range (end date ≥ start date)

3. **Variables List**
   - Implement multiple entry field for variables
   - Consider autocomplete against MINT variable catalog

## Testing and Validation

- Test form submission with various spatial coverage selections
- Verify data is stored and retrieved correctly
- Ensure backward compatibility with existing datasets
- Validate that MINT can correctly interpret the fields
- Test import/export functionality

## Priority and Timeline
High priority - Required for ensuring compatibility with MINT modeling tools.
Estimated timeline: 2 weeks for implementation and testing.
