### ISSUE TITLE
Implement Spatial Coverage Selector with Bounding Box Approach

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/ckan-docker#51]
# Implement Spatial Coverage Selector with Bounding Box Approach

## Description
As part of making our datasets MINT-compatible (see parent issue #50), we need to implement a spatial coverage selector using a bounding box approach. For the initial implementation, we'll start with a simplified manual input approach using text fields for coordinates.

### Core Functionality
- Implement a `spatial_coverage_selector` preset for ckan-scheming
- Use a bounding box approach (min/max latitude/longitude) for defining spatial coverage
- Start with manual coordinate entry (text fields) for the initial version
- Store data in a standardized GeoJSON format compatible with MINT

### User Interface - Manual Coordinate Input Fields
- Four input fields for manual entry:
  - North (max latitude)
  - South (min latitude)
  - East (max longitude)
  - West (min longitude)
- Add clear labels and help text for each field
- Add validation to ensure valid coordinate ranges:
  - Latitude: -90 to 90 degrees
  - Longitude: -180 to 180 degrees
- Add validation to ensure North > South and East > West

### Technical Implementation
- Create necessary templates: `spatial_coverage.html` and `spatial_coverage_display.html`
- Create validators for the coordinate fields
- Add CSS styling to match our existing CKAN theme
- Ensure the field correctly saves and loads with dataset records
- Convert the four coordinate values to a proper GeoJSON Polygon for storage

### Help Text Examples
- **North Latitude**: "Northern boundary in decimal degrees (90° to -90°). Example: 42.5234"
- **South Latitude**: "Southern boundary in decimal degrees (90° to -90°). Must be less than North Latitude. Example: 38.9876"
- **East Longitude**: "Eastern boundary in decimal degrees (180° to -180°). Example: -75.4321"
- **West Longitude**: "Western boundary in decimal degrees (180° to -180°). Must be less than East Longitude. Example: -80.1234"

### General Help Text
"Define the geographic boundaries of your dataset using decimal degree coordinates. The bounding box is the smallest rectangle that completely contains all the data in your dataset."

## Schema Implementation
```yaml
- field_name: spatial_coverage_north
  label: North Latitude
  form_placeholder: "90.0 to -90.0"
  help_text: "Northern boundary in decimal degrees (90° to -90°). Example: 42.5234"
  validators: spatial_latitude
  required: false

- field_name: spatial_coverage_south
  label: South Latitude
  form_placeholder: "90.0 to -90.0"
  help_text: "Southern boundary in decimal degrees (90° to -90°). Must be less than North Latitude. Example: 38.9876"
  validators: spatial_latitude
  required: false

- field_name: spatial_coverage_east
  label: East Longitude
  form_placeholder: "180.0 to -180.0"
  help_text: "Eastern boundary in decimal degrees (180° to -180°). Example: -75.4321"
  validators: spatial_longitude
  required: false

- field_name: spatial_coverage_west
  label: West Longitude
  form_placeholder: "180.0 to -180.0"
  help_text: "Western boundary in decimal degrees (180° to -180°). Must be less than East Longitude. Example: -80.1234"
  validators: spatial_longitude
  required: false
```

## Custom Validators
We'll need to implement the following validators:
1. `spatial_latitude` - Ensures value is a number between -90 and 90
2. `spatial_longitude` - Ensures value is a number between -180 and 180
3. `spatial_north_south` - Ensures North latitude > South latitude (when both are provided)
4. `spatial_east_west` - Ensures East longitude > West longitude (when both are provided)

## GeoJSON Conversion
When saving the dataset, we'll need to convert the four coordinate values to a proper GeoJSON Polygon. Example:

```json
{
  "type": "Feature",
  "properties": {
    "coverage_type": "bounding_box"
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [west, south],
        [east, south],
        [east, north],
        [west, north],
        [west, south]
      ]
    ]
  }
}
```

## Future Enhancement
In a future iteration, we can add:
- Interactive map component for drawing the bounding box
- GeoJSON import/export functionality
- Visual display of the bounding box on a map
- Address or place name search functionality

## Acceptance Criteria
- [ ] Four coordinate input fields appear correctly in dataset forms
- [ ] Input validation ensures coordinates are in valid ranges
- [ ] Input validation ensures North > South and East > West (when both values are present)
- [ ] Coordinates are converted to proper GeoJSON for storage
- [ ] Stored GeoJSON includes the proper feature properties
- [ ] Coordinates display correctly on dataset view pages
- [ ] GeoJSON is accessible through the CKAN API
- [ ] MINT can correctly interpret the spatial coverage information

## Parent Issue
This is a sub-task of #50: Add MINT-Compatible Fields to Default Dataset Schema
