### ISSUE TITLE
Implement Temporal Coverage Fields for MINT Compatibility

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/ckan-docker#52]
# Implement Temporal Coverage Fields for MINT Compatibility

## Description
As part of making our datasets MINT-compatible (see parent issue #50), we need to implement temporal coverage fields that allow users to specify the time period covered by their datasets. These fields are essential for proper integration with MINT's temporal modeling capabilities.

### Core Functionality
- Add two date fields to the dataset schema:
  - `temporal_coverage_start`: The beginning of the time period
  - `temporal_coverage_end`: The end of the time period
- Ensure proper date handling and storage in ISO format
- Implement validation to ensure start date is before or equal to end date
- Make fields accessible through the CKAN API

### User Interface
- Implement date picker controls for both fields
- Provide clear labeling and help text
- Include calendar popup for easy date selection
- Support manual entry with validation
- Show error messages for invalid date ranges

### Technical Implementation
- Add the fields to the ckan-scheming schema
- Create or use existing date validation functions
- Implement custom validation for date range (start ≤ end)
- Update templates to properly display the date range on dataset view pages
- Ensure values are correctly saved and retrieved from the database

## Schema Implementation
```yaml
- field_name: temporal_coverage_start
  label: Temporal Coverage Start
  preset: date
  form_placeholder: "YYYY-MM-DD"
  help_text: "The starting date of the time period covered by the dataset"
  required: false

- field_name: temporal_coverage_end
  label: Temporal Coverage End
  preset: date
  form_placeholder: "YYYY-MM-DD"
  help_text: "The ending date of the time period covered by the dataset"
  required: false
```

## Custom Validation
We need to create a validator that:
1. Ensures dates are in valid format
2. Validates that start date is before or equal to end date
3. Handles empty values appropriately (if one date is provided, the other may be optional)

## Display Considerations
- Format dates in a human-readable way on display (e.g., "January 1, 2023 to December 31, 2023")
- Consider adding visual indicators for datasets with temporal coverage (such as a calendar icon)
- Ensure dates are displayed in the user's local timezone when appropriate

## Acceptance Criteria
- [ ] Date fields appear correctly in the dataset creation and edit forms
- [ ] Date picker works properly for selecting dates
- [ ] Validation prevents invalid date ranges (start date after end date)
- [ ] Dates are stored in ISO format in the database
- [ ] Dates display correctly on dataset view pages
- [ ] Dates are accessible through the CKAN API
- [ ] MINT can correctly interpret the temporal coverage information

## Parent Issue
This is a sub-task of #50: Add MINT-Compatible Fields to Default Dataset Schema
