### ISSUE TITLE
Implement MINT Standard Variables Field for Datasets

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/ckan-docker#53]
# Implement MINT Standard Variables Field for Datasets

## Description
As part of making our datasets MINT-compatible (see parent issue #50), we need to implement a field for MINT standard variables. This field will allow users to specify which standardized variables are contained in their datasets, making them discoverable and usable in MINT modeling workflows.

### Core Functionality
- Implement a multiple-entry field for standard variables
- Support linking to the MINT standard variables catalog
- Store values in a format that MINT can interpret
- Allow for multiple variable entries per dataset

### User Interface
- Create a clean, intuitive interface for adding multiple variables
- Include reference link to MINT standard variables catalog
- Support search functionality to find variables if possible
- Allow for adding, editing, and removing variables
- Display a summary of added variables

### Technical Implementation
- Add the field to the ckan-scheming schema
- Use the `multiple_text` preset as the base implementation
- Extend functionality as needed for better usability
- Consider adding autocomplete against the MINT variable catalog API
- Store variables in a consistent format

## Schema Implementation
```yaml
- field_name: mint_standard_variables
  label: MINT Standard Variables
  preset: multiple_text
  form_placeholder: "e.g., air__daily_max_of_temperature"
  help_text: "Enter standardized variable names used in this dataset. See the <a href='https://api.models.mint.tacc.utexas.edu/v1.8.0/standardvariables?username=mint@isi.edu' target='_blank'>list of standard variables</a>."
  required: false
```

## Optional Enhancements
If time permits, consider these enhancements:
1. **Autocomplete Integration**:
   - Integrate with MINT API to provide autocomplete for variable names
   - Include descriptions and units when selecting variables

2. **Variable Validation**:
   - Add validation to ensure variables entered match the MINT standard variables
   - Provide warnings for non-standard variables

3. **Variable Grouping**:
   - Add support for grouping variables by category
   - Provide a hierarchical selection interface

## Display Considerations
- Display variables in a clean, organized list on dataset pages
- Add links from variable names to their definitions in MINT
- Consider adding icons or visual indicators for different variable types

## Acceptance Criteria
- [ ] Multiple variable input field appears correctly in dataset forms
- [ ] Users can add, edit, and remove variables
- [ ] Help text includes link to MINT standard variables list
- [ ] Variables are stored correctly in the database
- [ ] Variables display properly on dataset view pages
- [ ] Variables are accessible through the CKAN API
- [ ] MINT can correctly identify and use the variables information

## Parent Issue
This is a sub-task of #50: Add MINT-Compatible Fields to Default Dataset Schema
